name: snapspot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^17.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  uuid: ^4.6.0
  intl: ^0.20.2
  get_it: ^9.2.1
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  image_picker: ^1.2.3
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  http_certificate_pinning: ^3.0.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.0
  device_info_plus: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
