# Generated by Django 5.1.15 on 2026-07-22 16:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số điện thoại')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Họ và tên')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Tiểu sử')),
                ('auth_provider', models.CharField(choices=[('LOCAL', 'Tài khoản thường (Email/Password)'), ('GOOGLE', 'Google Sign-In'), ('APPLE', 'Apple Sign-In')], default='LOCAL', max_length=20, verbose_name='Phương thức đăng nhập')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('apple_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Apple ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('PENDING_VERIFICATION', 'Chờ xác thực Email/Phone'), ('TEMPORARILY_SUSPENDED', 'Tạm khóa'), ('PERMANENTLY_BANNED', 'Khóa vĩnh viễn'), ('PENDING_DELETION', 'Chờ xóa tài khoản')], default='ACTIVE', max_length=30, verbose_name='Trạng thái tài khoản')),
                ('banned_until', models.DateTimeField(blank=True, null=True, verbose_name='Tạm khóa đến')),
                ('ban_reason', models.TextField(blank=True, null=True, verbose_name='Lý do khóa')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Đã xác thực Email')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Đã xác thực Số điện thoại')),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='Bật bảo mật 2 lớp (2FA)')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đổi mật khẩu')),
                ('pending_deletion_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm yêu cầu xóa')),
                ('is_private', models.BooleanField(default=False, help_text='Chỉ bạn bè được duyệt mới xem được bài đăng & vị trí', verbose_name='Tài khoản riêng tư')),
                ('hide_exact_location', models.BooleanField(default=False, help_text='Chỉ hiển thị tên địa danh/quận huyện, ẩn số nhà GPS', verbose_name='Ẩn tọa độ GPS chính xác')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Số bài đăng')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='Số người theo dõi')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='Số người đang theo dõi')),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='Hoạt động lần cuối')),
                ('language', models.CharField(default='vi', max_length=10, verbose_name='Ngôn ngữ ứng dụng')),
                ('theme_mode', models.CharField(default='system', max_length=10, verbose_name='Chế độ giao diện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo tài khoản')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Danh sách người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Đăng nhập thành công'), ('LOGIN_FAILED', 'Đăng nhập thất bại'), ('PASSWORD_CHANGE', 'Thay đổi mật khẩu'), ('ACCOUNT_SUSPENDED', 'Tài khoản bị khóa'), ('TOKEN_REUSE_DETECTED', 'Phát hiện lạm dụng Token'), ('ACCOUNT_DELETION_REQUESTED', 'Yêu cầu xóa tài khoản'), ('TWO_FACTOR_VERIFIED', 'Xác thực 2FA thành công')], max_length=50, verbose_name='Loại sự kiện bảo mật')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Trình duyệt / Thiết bị')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Chi tiết sự kiện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm ghi nhận')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Nhật ký bảo mật',
                'verbose_name_plural': 'Nhật ký sự kiện bảo mật',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Tên thiết bị')),
                ('os_info', models.CharField(blank=True, max_length=100, verbose_name='Hệ điều hành')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('refresh_token_jti', models.CharField(max_length=255, unique=True, verbose_name='Mã Refresh Token (JTI)')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='Hoạt động lần cuối')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái phiên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo phiên')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiên đăng nhập',
                'verbose_name_plural': 'Quản lý phiên đăng nhập',
                'ordering': ['-last_active_at'],
            },
        ),
    ]
