server {
    listen 80;
    server_name localhost;

    client_max_body_size 50M;

    # Forward tất cả API Requests tới Django Backend Container
    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Phục vụ Static Files trực tiếp qua Nginx
    location /static/ {
        alias /app/staticfiles/;
    }

    # Phục vụ Media Files (Avatar/Uploads) trực tiếp qua Nginx
    location /media/ {
        alias /app/media/;
    }
}
